[package]
name = "flyer"
version = "0.0.35"
authors = ["Themba Lucas Ngubeni <thembangubeni04@email.com>"]
license = "MIT"
description = "HTTP framework for rust"
readme = "README.md"
homepage = "https://github.com/lucas11776-golang/flyer"
repository = "https://github.com/lucas11776-golang/flyer"
keywords = ["http", "web", "framework"]
categories = ["web-programming", "web-programming::http-server", "web-programming::websocket"]
edition = "2024"

[dependencies]
openssl = "0.10.74"
rustls = "0.23.35"
reqwest = { version = "0.12.24", default-features = false, features = ["rustls-tls"] }
urlencoding = "2.1.3"
regex = "1.12.2"
once_cell = "1.21.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

tokio = { version = "1.48.0", features = ["full"] }
h2 = "0.4.12"
http = "1.3.1"
bytes = "1"
tokio-openssl = "0.6.5"
tokio-scoped = "0.2.0"
tokio-rustls = "0.26.4"
futures-util = "0.3.31"
multer = "3.1.0"
uuid = "1.18.1"
aes-gcm = "0.10.3"
lazy_static = "1.5.0"
base64 = "0.22.1"
tera = "1.20.1"

quinn = "0.11.9"   
h3 = "0.0.8"   
h3-quinn = "0.0.10"      
tracing = "0.1.41"
structopt = "0.3.26"
tracing-subscriber = "0.3.20"
ctrlc = "3.5.1"
sha1 = "0.10.6"

tokio-tungstenite = "0.28.0"
tungstenite = "0.28.0"
event-emitter-rs = "0.1.4"
async-event-emitter = "0.1.5"
futures = "0.3.31"